extends Reference
# Named points of interest. Each POI is laid out in its own frame:
#   local +X points away from the island centre, local +Z is "right" of that.
# Props: {res, at (Vector2), yaw (deg, local), y (extra height), tint, harvest, building,
#         face_center (door faces the POI middle), spin ("blades" | "dish")}
# Chests / items may be given relative to a prop: "in": index into props, and then "at" is
# in that prop's own frame (door side = +Z), otherwise "at" is POI-local.

const POIS := [
	{
		"id": "docks", "name": "SALTWORKS DOCKS", "angle": 20.0, "mode": "shore", "inland": 22.0, "zone": 34.0,
		"props": [
			{"res": "warehouse", "at": Vector2(-14, 0), "yaw": 90, "harvest": "metal", "building": true},
			{"res": "container", "at": Vector2(-3, -15), "yaw": 0, "tint": Color(0.75, 0.2, 0.15), "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, -12.4), "yaw": 0, "tint": Color(0.2, 0.4, 0.7), "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, -15), "y": 2.6, "yaw": 0, "tint": Color(0.9, 0.6, 0.15), "harvest": "metal"},
			{"res": "container", "at": Vector2(2, -14), "yaw": 0, "tint": Color(0.2, 0.55, 0.3), "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, 14), "yaw": 90, "tint": Color(0.6, 0.2, 0.5), "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, 14), "y": 2.6, "yaw": 90, "tint": Color(0.2, 0.6, 0.7), "harvest": "metal"},
			{"res": "crane", "at": Vector2(9, 11), "yaw": 90, "harvest": "metal"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
			{"at": Vector2(12, -6), "yaw": 90, "kind": "chest"},
		],
		"items": [Vector2(0, 6), Vector2(8, 2), Vector2(14, -3), Vector2(-8, 9)],
		"pier": {"from": 16.0, "length": 34.0, "width": 5.0},
		"vehicles": [{"kind": "boat", "at": Vector2(30, 7), "yaw": 0}, {"kind": "buggy", "at": Vector2(4, 4), "yaw": 90}],
	},
	{
		"id": "lodge", "name": "PINE RIDGE LODGE", "angle": 150.0, "mode": "hill", "rmin": 74.0, "rmax": 94.0, "zone": 36.0,
		"props": [
			{"res": "lodge", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-1, -22), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-1, 22), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-19, -12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-19, 13), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(16, 18), "yaw": 0, "harvest": "wood"},
			{"res": "fence", "at": Vector2(10, -26), "yaw": 0, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(13, -26), "yaw": 0, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(16, -26), "yaw": 0, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-4.5, -3.2), "kind": "chest"},
			{"in": 0, "at": Vector2(4.5, -3.2), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.0), "kind": "ammo_box"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 3, "at": Vector2(-1.8, -1.6), "kind": "chest"},
		],
		"items": [Vector2(2, 4), Vector2(-6, 8), Vector2(9, -8), Vector2(-10, 0)],
		"vehicles": [{"kind": "quad", "at": Vector2(12, 4), "yaw": 90}],
	},
	{
		"id": "foundry", "name": "RUSTY FOUNDRY", "angle": 215.0, "mode": "flat", "rmin": 76.0, "rmax": 96.0, "zone": 38.0,
		"props": [
			{"res": "warehouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "chimney", "at": Vector2(-18, -14), "yaw": 0, "harvest": "metal"},
			{"res": "chimney", "at": Vector2(-18, 14), "yaw": 0, "harvest": "metal"},
			{"res": "tank", "at": Vector2(14, -16), "yaw": 0, "harvest": "metal"},
			{"res": "tank", "at": Vector2(14, 16), "yaw": 0, "harvest": "metal"},
			{"res": "container", "at": Vector2(12, 0), "yaw": 90, "tint": Color(0.7, 0.35, 0.12), "harvest": "metal"},
			{"res": "container", "at": Vector2(-22, 0), "yaw": 90, "tint": Color(0.25, 0.4, 0.55), "harvest": "metal"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
			{"at": Vector2(8, 10), "yaw": 0, "kind": "chest"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 6), Vector2(8, -6)],
		"vehicles": [{"kind": "buggy", "at": Vector2(18, 4), "yaw": 90}],
	},
	{
		"id": "farm", "name": "GOLDEN ACRES", "angle": 280.0, "mode": "flat", "rmin": 74.0, "rmax": 94.0, "zone": 38.0,
		"props": [
			{"res": "barn", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "silo", "at": Vector2(-15, -11), "yaw": 0, "harvest": "metal"},
			{"res": "silo", "at": Vector2(-15, 0), "yaw": 0, "harvest": "metal"},
			{"res": "windmill", "at": Vector2(16, 14), "yaw": -90, "harvest": "wood", "spin": "blades"},
			{"res": "house_a", "at": Vector2(14, -8), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "haystack", "at": Vector2(9, 12), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(12, 9), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(-6, 16), "yaw": 0, "harvest": "wood"},
			{"res": "fence", "at": Vector2(-24, 14), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(-24, 17), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(-24, 20), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3, -5.5), "kind": "chest"},
			{"in": 0, "at": Vector2(3, -5.5), "kind": "ammo_box"},
			{"in": 4, "at": Vector2(-2.7, -2.3), "kind": "chest"},
		],
		"items": [Vector2(0, 3), Vector2(8, 4), Vector2(-9, 6)],
		"vehicles": [{"kind": "quad", "at": Vector2(6, 8), "yaw": 0}],
	},
	{
		"id": "bunker", "name": "IRON BUNKER", "angle": 330.0, "mode": "hill", "rmin": 78.0, "rmax": 98.0, "zone": 34.0,
		"props": [
			{"res": "bunker", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "radar", "at": Vector2(-17, 2), "yaw": 0, "harvest": "metal", "spin": "dish"},
			{"res": "watchtower", "at": Vector2(17, 18), "yaw": 0, "harvest": "wood"},
			{"res": "watchtower", "at": Vector2(17, -18), "yaw": 0, "harvest": "wood"},
			{"res": "sandbags", "at": Vector2(7, -5), "yaw": 90, "harvest": "stone"},
			{"res": "sandbags", "at": Vector2(7, 5), "yaw": 90, "harvest": "stone"},
			{"res": "sandbags", "at": Vector2(11, 0), "yaw": 0, "harvest": "stone"},
			{"res": "crate", "at": Vector2(12, 8), "yaw": 20, "harvest": "wood"},
			{"res": "crate", "at": Vector2(13.4, 9.0), "yaw": 55, "harvest": "wood"},
			{"res": "crate", "at": Vector2(12.4, -9), "yaw": 10, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(0, -2.8), "kind": "vault"},
			{"in": 0, "at": Vector2(-3.6, -2.8), "kind": "chest"},
			{"in": 0, "at": Vector2(3.6, -2.8), "kind": "ammo_box"},
			{"at": Vector2(14, 4), "yaw": 90, "kind": "ammo_box"},
		],
		"items": [Vector2(10, -2), Vector2(-9, 8)],
		"boss": {"at": Vector2(9, 3)},
		"vault": {"at": Vector2(-6, -30), "yaw": 0.0},
		"helipad": Vector2(-8, -20),
		"vehicles": [{"kind": "buggy", "at": Vector2(-8, 12), "yaw": 0}],
	},
	{
		"id": "lighthouse", "name": "LIGHTHOUSE POINT", "angle": 85.0, "mode": "shore", "inland": 14.0, "zone": 24.0,
		"props": [
			{"res": "lighthouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "stone"},
			{"res": "keeper_house", "at": Vector2(-13, 8), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "fence", "at": Vector2(-8, -10), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(-8, -13), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 1, "at": Vector2(-1.5, -1.3), "kind": "chest"},
			{"at": Vector2(4, -4), "yaw": 0, "kind": "ammo_box"},
		],
		"items": [Vector2(5, 6), Vector2(-4, -6)],
		"vehicles": [{"kind": "boat", "at": Vector2(20, 9), "yaw": 0}],
	},
	{
		"id": "marina", "name": "BLACKWATER MARINA", "angle": 50.0, "mode": "shore", "inland": 20.0, "zone": 32.0,
		"props": [
			{"res": "warehouse", "at": Vector2(-14, 0), "yaw": 90, "harvest": "metal", "building": true},
			{"res": "crane", "at": Vector2(8, 12), "yaw": 90, "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, -14), "yaw": 0, "tint": Color(0.2, 0.45, 0.7), "harvest": "metal"},
			{"res": "container", "at": Vector2(-3, -11.4), "yaw": 0, "tint": Color(0.8, 0.5, 0.15), "harvest": "metal"},
			{"res": "container", "at": Vector2(2, -13), "yaw": 0, "tint": Color(0.55, 0.2, 0.2), "harvest": "metal"},
			{"res": "tank", "at": Vector2(12, -14), "yaw": 0, "harvest": "metal"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
			{"at": Vector2(12, -8), "yaw": 90, "kind": "chest"},
		],
		"items": [Vector2(0, 6), Vector2(8, 2), Vector2(-8, 9)],
		"pier": {"from": 14.0, "length": 30.0, "width": 4.0},
		"vehicles": [{"kind": "boat", "at": Vector2(26, 6), "yaw": 0}, {"kind": "buggy", "at": Vector2(4, 6), "yaw": 90}],
	},
	{
		"id": "hollow", "name": "WINDMILL HOLLOW", "angle": 108.0, "mode": "flat", "rmin": 84.0, "rmax": 112.0, "zone": 36.0,
		"props": [
			{"res": "barn", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "windmill", "at": Vector2(16, 14), "yaw": -90, "harvest": "wood", "spin": "blades"},
			{"res": "windmill", "at": Vector2(-18, 13), "yaw": 90, "harvest": "wood", "spin": "blades"},
			{"res": "silo", "at": Vector2(-15, -11), "yaw": 0, "harvest": "metal"},
			{"res": "silo", "at": Vector2(-15, 0), "yaw": 0, "harvest": "metal"},
			{"res": "house_a", "at": Vector2(14, -8), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "haystack", "at": Vector2(9, 12), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(-6, 17), "yaw": 0, "harvest": "wood"},
			{"res": "fence", "at": Vector2(-24, 14), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(-24, 17), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3, -5.5), "kind": "chest"},
			{"in": 0, "at": Vector2(3, -5.5), "kind": "ammo_box"},
			{"in": 5, "at": Vector2(-2.7, -2.3), "kind": "chest"},
		],
		"items": [Vector2(0, 3), Vector2(8, 4), Vector2(-9, 6)],
		"vehicles": [{"kind": "quad", "at": Vector2(6, 8), "yaw": 0}],
	},
	{
		"id": "quarry", "name": "GRANITE QUARRY", "angle": 183.0, "mode": "hill", "rmin": 86.0, "rmax": 114.0, "zone": 36.0,
		"props": [
			{"res": "warehouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "crane", "at": Vector2(14, -14), "yaw": 0, "harvest": "metal"},
			{"res": "container", "at": Vector2(12, 4), "yaw": 90, "tint": Color(0.7, 0.45, 0.15), "harvest": "metal"},
			{"res": "container", "at": Vector2(-22, 0), "yaw": 90, "tint": Color(0.3, 0.45, 0.35), "harvest": "metal"},
			{"res": "tank", "at": Vector2(15, 14), "yaw": 0, "harvest": "metal"},
			{"res": "sandbags", "at": Vector2(8, -6), "yaw": 90, "harvest": "stone"},
			{"res": "sandbags", "at": Vector2(8, 6), "yaw": 90, "harvest": "stone"},
			{"res": "crate", "at": Vector2(-12, 10), "yaw": 20, "harvest": "wood"},
			{"res": "crate", "at": Vector2(-13.4, 11.0), "yaw": 55, "harvest": "wood"},
			{"res": "watchtower", "at": Vector2(-18, 16), "yaw": 0, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
			{"at": Vector2(12, -6), "yaw": 0, "kind": "ammo_box"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 6), Vector2(8, -2)],
		"vehicles": [{"kind": "buggy", "at": Vector2(18, 4), "yaw": 90}],
	},
	{
		"id": "mesa", "name": "EMBER MESA", "angle": 247.0, "mode": "hill", "rmin": 88.0, "rmax": 116.0, "zone": 34.0,
		"props": [
			{"res": "cabin", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-1, -20), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-1, 20), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-18, -10), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(14, 16), "yaw": 0, "harvest": "wood"},
			{"res": "watchtower", "at": Vector2(14, -16), "yaw": 0, "harvest": "wood"},
			{"res": "chimney", "at": Vector2(-18, 14), "yaw": 0, "harvest": "metal"},
			{"res": "fence", "at": Vector2(10, -26), "yaw": 0, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(13, -26), "yaw": 0, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 2, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 3, "at": Vector2(-1.8, -1.6), "kind": "ammo_box"},
			{"at": Vector2(8, 2), "yaw": 0, "kind": "ammo_box"},
		],
		"items": [Vector2(2, 4), Vector2(-6, 8), Vector2(9, -8)],
		"vehicles": [{"kind": "quad", "at": Vector2(10, 4), "yaw": 90}],
	},
	{
		"id": "frost", "name": "FROSTBITE FLATS", "angle": 305.0, "mode": "flat", "rmin": 88.0, "rmax": 114.0, "zone": 36.0,
		"props": [
			{"res": "house_b", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-18, -10), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-18, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(14, -14), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "radar", "at": Vector2(16, 10), "yaw": 0, "harvest": "metal", "spin": "dish"},
			{"res": "crate", "at": Vector2(9, 6), "yaw": 15, "harvest": "wood"},
			{"res": "crate", "at": Vector2(10.4, 7.0), "yaw": 50, "harvest": "wood"},
			{"res": "fence", "at": Vector2(-8, 20), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 1, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 2, "at": Vector2(-2.7, -2.3), "kind": "ammo_box"},
			{"in": 3, "at": Vector2(-1.8, -1.6), "kind": "chest"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 6), Vector2(8, -4)],
		"vehicles": [{"kind": "buggy", "at": Vector2(12, 0), "yaw": 90}],
	},
	{
		"id": "cove", "name": "CRESCENT COVE", "angle": 132.0, "mode": "shore", "inland": 16.0, "zone": 28.0,
		"props": [
			{"res": "keeper_house", "at": Vector2(-12, 8), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-14, -12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(8, 16), "yaw": 0, "harvest": "wood"},
			{"res": "crate", "at": Vector2(2, -8), "yaw": 30, "harvest": "wood"},
			{"res": "crate", "at": Vector2(3.4, -7.0), "yaw": 70, "harvest": "wood"},
			{"res": "fence", "at": Vector2(-6, -18), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-1.5, -1.3), "kind": "chest"},
			{"in": 1, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"at": Vector2(6, -4), "yaw": 0, "kind": "ammo_box"},
		],
		"items": [Vector2(5, 6), Vector2(-4, -6)],
		"pier": {"from": 10.0, "length": 26.0, "width": 4.0},
		"vehicles": [{"kind": "boat", "at": Vector2(22, 8), "yaw": 0}],
	},
	{
		"id": "skyline", "name": "SKYLINE HEIGHTS", "angle": 355.0, "mode": "flat", "rmin": 92.0, "rmax": 120.0, "zone": 50.0,
		"props": [
			{"res": "highrise_c", "at": Vector2(0, 0), "yaw": 0, "harvest": "stone", "building": true},
			{"res": "highrise_b", "at": Vector2(-27, -5), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "highrise_b", "at": Vector2(27, 5), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "highrise_a", "at": Vector2(-2, -27), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "highrise_a", "at": Vector2(3, 27), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "highrise_a", "at": Vector2(-26, 24), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "highrise_b", "at": Vector2(26, -24), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.5, 3.5), "kind": "chest"},
			{"in": 0, "at": Vector2(3.5, 3.5), "kind": "ammo_box"},
			{"in": 0, "at": Vector2(-3.5, 3.5), "y": 6.7, "kind": "chest"},
			{"in": 0, "at": Vector2(3.5, 3.5), "y": 13.5, "kind": "chest"},
			{"in": 0, "at": Vector2(-3.5, 3.5), "y": 23.7, "kind": "chest"},
			{"in": 0, "at": Vector2(3.5, 3.5), "y": 40.8, "kind": "supply"},
			{"in": 1, "at": Vector2(-3.0, 3.5), "kind": "chest"},
			{"in": 1, "at": Vector2(3.0, 3.5), "y": 10.2, "kind": "chest"},
			{"in": 1, "at": Vector2(-3.0, 3.5), "y": 30.6, "kind": "chest"},
			{"in": 2, "at": Vector2(-3.0, 3.5), "kind": "chest"},
			{"in": 2, "at": Vector2(3.0, 3.5), "y": 17.0, "kind": "chest"},
			{"in": 2, "at": Vector2(3.0, 3.5), "y": 30.6, "kind": "chest"},
			{"in": 3, "at": Vector2(-3.0, 3.0), "kind": "chest"},
			{"in": 3, "at": Vector2(3.0, 3.0), "y": 10.2, "kind": "chest"},
			{"in": 4, "at": Vector2(-3.0, 3.0), "kind": "chest"},
			{"in": 4, "at": Vector2(3.0, 3.0), "y": 13.6, "kind": "chest"},
			{"in": 5, "at": Vector2(-3.0, 3.0), "kind": "chest"},
			{"in": 5, "at": Vector2(3.0, 3.0), "y": 17.0, "kind": "chest"},
			{"in": 6, "at": Vector2(-3.0, 3.5), "kind": "ammo_box"},
			{"in": 6, "at": Vector2(3.0, 3.5), "y": 20.4, "kind": "chest"},
			{"at": Vector2(14, 14), "kind": "chest"},
			{"at": Vector2(-14, -14), "kind": "chest"},
		],
		"items": [Vector2(14, 0), Vector2(-14, 2), Vector2(0, 14), Vector2(2, -14), Vector2(15, -14), Vector2(-15, 15)],
		"vehicles": [{"kind": "buggy", "at": Vector2(14, -2), "yaw": 90}, {"kind": "quad", "at": Vector2(-14, 6), "yaw": 0}],
	},
	{
		"id": "dune", "name": "DUSTY OUTPOST", "angle": 68.0, "mode": "flat", "rmin": 100.0, "rmax": 114.0, "zone": 34.0,
		"props": [
			{"res": "house_a", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-15, -9), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-15, 10), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(14, -12), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(10, 11), "yaw": 0, "harvest": "wood"},
			{"res": "sandbags", "at": Vector2(8, -4), "yaw": 90, "harvest": "stone", "decor": true},
			{"res": "crate", "at": Vector2(6, 8), "yaw": 20, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 2, "at": Vector2(-1.8, -1.6), "kind": "ammo_box"},
			{"at": Vector2(12, 4), "yaw": 0, "kind": "chest"},
		],
		"items": [Vector2(4, 6), Vector2(-7, 3), Vector2(9, -7)],
		"vehicles": [{"kind": "quad", "at": Vector2(12, 0), "yaw": 90}],
	},
	{
		"id": "ridge", "name": "RIDGEWAY LOOKOUT", "angle": 196.0, "mode": "hill", "rmin": 100.0, "rmax": 116.0, "zone": 32.0,
		"props": [
			{"res": "cabin", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(12, 8), "yaw": 0, "harvest": "wood"},
			{"res": "radar", "at": Vector2(-14, -6), "yaw": 0, "harvest": "metal", "spin": "dish"},
			{"res": "container", "at": Vector2(-8, 12), "yaw": 0, "tint": Color(0.3, 0.5, 0.35), "harvest": "metal"},
			{"res": "crate", "at": Vector2(6, -8), "yaw": 30, "harvest": "wood"},
			{"res": "crate", "at": Vector2(7.4, -7), "yaw": 70, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"at": Vector2(10, 4), "yaw": 0, "kind": "ammo_box"},
			{"at": Vector2(-10, -10), "yaw": 0, "kind": "chest"},
		],
		"items": [Vector2(3, 6), Vector2(-6, 4), Vector2(8, -2)],
		"vehicles": [],
	},
	{
		"id": "cinder", "name": "CINDER YARD", "angle": 262.0, "mode": "flat", "rmin": 100.0, "rmax": 114.0, "zone": 36.0,
		"props": [
			{"res": "warehouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "tank", "at": Vector2(16, -15), "yaw": 0, "harvest": "metal"},
			{"res": "tank", "at": Vector2(16, 15), "yaw": 0, "harvest": "metal"},
			{"res": "chimney", "at": Vector2(-18, 0), "yaw": 0, "harvest": "metal"},
			{"res": "container", "at": Vector2(10, 0), "yaw": 90, "tint": Color(0.75, 0.3, 0.12), "harvest": "metal"},
			{"res": "container", "at": Vector2(-12, 14), "yaw": 0, "tint": Color(0.25, 0.4, 0.6), "harvest": "metal"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 6), Vector2(8, -6)],
		"vehicles": [{"kind": "buggy", "at": Vector2(20, 2), "yaw": 90}],
	},
	{
		"id": "glacier", "name": "GLACIER LODGE", "angle": 320.0, "mode": "flat", "rmin": 100.0, "rmax": 116.0, "zone": 34.0,
		"props": [
			{"res": "lodge", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-16, -12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-16, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "fence", "at": Vector2(12, 14), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "crate", "at": Vector2(10, -6), "yaw": 25, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "ammo_box"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 2, "at": Vector2(-1.8, -1.6), "kind": "chest"},
		],
		"items": [Vector2(5, 6), Vector2(-6, 2), Vector2(8, -8)],
		"vehicles": [{"kind": "quad", "at": Vector2(14, 0), "yaw": 90}],
	},
	{
		"id": "orchard", "name": "ORCHARD ROW", "angle": 28.0, "mode": "flat", "rmin": 98.0, "rmax": 112.0, "zone": 36.0,
		"props": [
			{"res": "barn", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "silo", "at": Vector2(-15, -4), "yaw": 0, "harvest": "metal"},
			{"res": "house_b", "at": Vector2(16, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "haystack", "at": Vector2(12, -10), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(-8, 16), "yaw": 0, "harvest": "wood"},
			{"res": "fence", "at": Vector2(-22, 14), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3, -5.5), "kind": "chest"},
			{"in": 0, "at": Vector2(3, -5.5), "kind": "ammo_box"},
			{"in": 2, "at": Vector2(-3.0, -2.5), "kind": "chest"},
		],
		"items": [Vector2(0, 4), Vector2(9, 4), Vector2(-9, 8)],
		"vehicles": [{"kind": "buggy", "at": Vector2(8, 10), "yaw": 0}],
	},
	{
		"id": "bureau", "name": "THE BUREAU", "angle": 40.0, "mode": "hill", "rmin": 70.0, "rmax": 100.0, "zone": 40.0,
		"props": [
			{"res": "warehouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "radar", "at": Vector2(-20, 6), "yaw": 0, "harvest": "metal", "spin": "dish"},
			{"res": "tower", "at": Vector2(15, -16), "yaw": 0, "harvest": "metal"},
			{"res": "watchtower", "at": Vector2(17, 17), "yaw": 0, "harvest": "wood"},
			{"res": "container", "at": Vector2(-14, -18), "yaw": 0, "tint": Color(0.15, 0.17, 0.2), "harvest": "metal"},
			{"res": "container", "at": Vector2(-14, 20), "yaw": 0, "tint": Color(0.15, 0.17, 0.2), "harvest": "metal"},
			{"res": "sandbags", "at": Vector2(9, -5), "yaw": 90, "harvest": "stone"},
			{"res": "sandbags", "at": Vector2(9, 5), "yaw": 90, "harvest": "stone"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(0, -4.4), "kind": "ammo_box"},
			{"at": Vector2(14, 2), "yaw": 90, "kind": "chest"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 4), Vector2(10, -2), Vector2(-4, -10)],
		"vault": {"at": Vector2(-4, 28), "yaw": 180.0},
		"boss": {"at": Vector2(8, 10), "name": "Agent Warden"},
		"helipad": Vector2(22, -2),
		"vehicles": [{"kind": "buggy", "at": Vector2(6, -12), "yaw": 90}],
	},
	{
		"id": "stronghold", "name": "STEALTH STRONGHOLD", "angle": 232.0, "mode": "hill", "rmin": 90.0, "rmax": 118.0, "zone": 36.0,
		"props": [
			{"res": "bunker", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(17, 16), "yaw": 0, "harvest": "wood"},
			{"res": "watchtower", "at": Vector2(17, -16), "yaw": 0, "harvest": "wood"},
			{"res": "watchtower", "at": Vector2(-17, 0), "yaw": 0, "harvest": "wood"},
			{"res": "sandbags", "at": Vector2(8, -5), "yaw": 90, "harvest": "stone"},
			{"res": "sandbags", "at": Vector2(8, 5), "yaw": 90, "harvest": "stone"},
			{"res": "crate", "at": Vector2(-10, 12), "yaw": 20, "harvest": "wood"},
			{"res": "crate", "at": Vector2(-11.4, 13.0), "yaw": 55, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.6, -2.8), "kind": "chest"},
			{"in": 0, "at": Vector2(3.6, -2.8), "kind": "ammo_box"},
			{"at": Vector2(12, 0), "yaw": 90, "kind": "chest"},
		],
		"items": [Vector2(10, 8), Vector2(-8, 8), Vector2(2, -10)],
		"vault": {"at": Vector2(-8, -26), "yaw": 0.0},
		"boss": {"at": Vector2(-6, 7), "name": "Warden Kane"},
		"vehicles": [{"kind": "quad", "at": Vector2(12, -8), "yaw": 90}],
	},
	{
		"id": "lagoon", "name": "LAZY LAGOON", "angle": 98.0, "mode": "shore", "inland": 18.0, "zone": 32.0,
		"props": [
			{"res": "house_b", "at": Vector2(-8, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-10, -17), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-10, 17), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-26, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(6, 18), "yaw": 0, "harvest": "wood"},
			{"res": "fence", "at": Vector2(2, -24), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 1, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 2, "at": Vector2(-2.7, -2.3), "kind": "ammo_box"},
			{"in": 3, "at": Vector2(-1.8, -1.6), "kind": "chest"},
		],
		"items": [Vector2(2, 6), Vector2(-4, 10), Vector2(6, -6)],
		"pier": {"from": 10.0, "length": 24.0, "width": 4.0},
		"vehicles": [{"kind": "boat", "at": Vector2(24, 6), "yaw": 0}],
	},
	{
		"id": "mire", "name": "MURKY MIRE", "angle": 170.0, "mode": "flat", "rmin": 84.0, "rmax": 110.0, "zone": 34.0,
		"props": [
			{"res": "cabin", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-1, -19), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-16, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "tower", "at": Vector2(14, 16), "yaw": 0, "harvest": "wood"},
			{"res": "tank", "at": Vector2(14, -14), "yaw": 0, "harvest": "metal"},
			{"res": "haystack", "at": Vector2(8, 4), "yaw": 0, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 2, "at": Vector2(-1.8, -1.6), "kind": "ammo_box"},
		],
		"items": [Vector2(4, 8), Vector2(-8, 4), Vector2(8, -8)],
		"vehicles": [{"kind": "quad", "at": Vector2(8, 10), "yaw": 0}],
	},
	{
		"id": "market", "name": "MARKET STREET", "angle": 300.0, "mode": "flat", "rmin": 92.0, "rmax": 116.0, "zone": 40.0,
		"props": [
			{"res": "warehouse", "at": Vector2(0, 0), "yaw": 0, "harvest": "metal", "building": true, "face_center": true},
			{"res": "house_b", "at": Vector2(-8, -24), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_b", "at": Vector2(-8, 24), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-24, -12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-24, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "highrise_a", "at": Vector2(-30, 0), "yaw": 0, "harvest": "stone", "building": true, "face_center": true},
			{"res": "crate", "at": Vector2(12, 4), "yaw": 10, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-6.5, -3.8), "kind": "chest"},
			{"in": 0, "at": Vector2(6.5, -3.8), "kind": "ammo_box"},
			{"in": 1, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 2, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 3, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 4, "at": Vector2(-2.7, -2.3), "kind": "ammo_box"},
			{"in": 5, "at": Vector2(-3.5, 3.5), "kind": "chest"},
		],
		"items": [Vector2(6, 8), Vector2(-4, 12), Vector2(6, -10), Vector2(-14, 0)],
		"vehicles": [{"kind": "buggy", "at": Vector2(14, -6), "yaw": 90}],
	},
	{
		"id": "springs", "name": "SULFUR SPRINGS", "angle": 340.0, "mode": "flat", "rmin": 78.0, "rmax": 104.0, "zone": 32.0,
		"props": [
			{"res": "house_a", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-3, -18), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_b", "at": Vector2(-14, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "windmill", "at": Vector2(14, 12), "yaw": -90, "harvest": "wood", "spin": "blades"},
			{"res": "fence", "at": Vector2(8, -20), "yaw": 0, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 1, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 2, "at": Vector2(-3.0, -2.5), "kind": "ammo_box"},
		],
		"items": [Vector2(5, 5), Vector2(-6, 8), Vector2(8, -6)],
		"vehicles": [{"kind": "quad", "at": Vector2(10, 0), "yaw": 90}],
	},
	{
		"id": "corner", "name": "CRAFTY CORNER", "angle": 120.0, "mode": "flat", "rmin": 74.0, "rmax": 104.0, "zone": 30.0,
		"props": [
			{"res": "house_b", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-14, -12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "cabin", "at": Vector2(-14, 12), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "watchtower", "at": Vector2(12, 14), "yaw": 0, "harvest": "wood"},
			{"res": "haystack", "at": Vector2(8, -10), "yaw": 0, "harvest": "wood"},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 1, "at": Vector2(-1.8, -1.6), "kind": "chest"},
			{"in": 2, "at": Vector2(-1.8, -1.6), "kind": "ammo_box"},
		],
		"items": [Vector2(4, 6), Vector2(-6, 6), Vector2(6, -6)],
		"vehicles": [{"kind": "buggy", "at": Vector2(10, 4), "yaw": 90}],
	},
	{
		"id": "bramble", "name": "BRAMBLE HEDGES", "angle": 205.0, "mode": "flat", "rmin": 96.0, "rmax": 116.0, "zone": 34.0,
		"props": [
			{"res": "house_b", "at": Vector2(0, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-3, 18), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-3, -18), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "house_a", "at": Vector2(-20, 0), "yaw": 0, "harvest": "wood", "building": true, "face_center": true},
			{"res": "fence", "at": Vector2(10, -10), "yaw": 90, "harvest": "wood", "decor": true},
			{"res": "fence", "at": Vector2(10, 10), "yaw": 90, "harvest": "wood", "decor": true},
		],
		"chests": [
			{"in": 0, "at": Vector2(-3.0, -2.5), "kind": "chest"},
			{"in": 1, "at": Vector2(-2.7, -2.3), "kind": "chest"},
			{"in": 2, "at": Vector2(-2.7, -2.3), "kind": "ammo_box"},
			{"in": 3, "at": Vector2(-2.7, -2.3), "kind": "chest"},
		],
		"items": [Vector2(5, 5), Vector2(-8, 8), Vector2(6, -8)],
		"vehicles": [{"kind": "quad", "at": Vector2(12, 0), "yaw": 90}],
	},
]

# Roads: pairs of POI ids (or "maple" for the town) drawn on the terrain and the map.
const ROADS := [
	["maple", "docks"], ["maple", "lodge"], ["maple", "foundry"], ["maple", "farm"], ["maple", "bunker"],
	["maple", "lighthouse"], ["docks", "lighthouse"], ["farm", "bunker"], ["foundry", "lodge"],
	["maple", "marina"], ["maple", "hollow"], ["maple", "quarry"], ["maple", "mesa"], ["maple", "frost"], ["maple", "cove"],
	["marina", "docks"], ["marina", "lighthouse"], ["cove", "bunker"], ["hollow", "lodge"], ["quarry", "foundry"],
	["mesa", "foundry"], ["frost", "farm"], ["frost", "mesa"], ["maple", "skyline"], ["skyline", "docks"], ["skyline", "bunker"], ["maple", "dune"], ["dune", "marina"], ["maple", "ridge"], ["ridge", "quarry"], ["maple", "cinder"], ["cinder", "mesa"], ["cinder", "farm"], ["maple", "glacier"], ["glacier", "frost"], ["glacier", "bunker"], ["maple", "orchard"], ["orchard", "docks"], ["orchard", "skyline"],
	["maple", "bureau"], ["bureau", "marina"], ["bureau", "dune"], ["maple", "stronghold"], ["stronghold", "mesa"], ["stronghold", "quarry"],
	["maple", "lagoon"], ["lagoon", "hollow"], ["lagoon", "marina"], ["maple", "mire"], ["mire", "quarry"], ["mire", "ridge"],
	["maple", "market"], ["market", "frost"], ["market", "skyline"], ["maple", "springs"], ["springs", "skyline"], ["springs", "orchard"],
	["maple", "corner"], ["corner", "hollow"], ["corner", "cove"], ["maple", "bramble"], ["bramble", "ridge"], ["bramble", "foundry"],
]
